-- VGS / Supabase first database setup
-- Run this entire file in Supabase -> SQL Editor -> New query.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  role text not null default 'client' check (role in ('client','admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile"
on public.profiles for select
to authenticated
using (auth.uid() = id);

-- Create a profile automatically whenever a new Supabase Auth user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.email
  )
  on conflict (id) do update set
    full_name = excluded.full_name,
    email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- After creating YOUR account, replace the email below with your real VGS admin email
-- and run this one statement to grant administrator access.
-- update public.profiles set role = 'admin' where email = 'YOUR-EMAIL@example.com';

-- Useful starter tables for the next phase.
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.profiles(id) on delete cascade,
  service text not null,
  project_name text,
  description text,
  budget numeric,
  deadline date,
  status text not null default 'pending' check (status in ('pending','approved','in_progress','completed','cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text,
  status text not null default 'active' check (status in ('active','completed','cancelled')),
  created_at timestamptz not null default now()
);

alter table public.bookings enable row level security;
alter table public.projects enable row level security;

drop policy if exists "Clients can view own bookings" on public.bookings;
create policy "Clients can view own bookings"
on public.bookings for select
to authenticated
using (auth.uid() = client_id);

drop policy if exists "Clients can create own bookings" on public.bookings;
create policy "Clients can create own bookings"
on public.bookings for insert
to authenticated
with check (auth.uid() = client_id);

drop policy if exists "Clients can view own projects" on public.projects;
create policy "Clients can view own projects"
on public.projects for select
to authenticated
using (auth.uid() = client_id);
