-- VGS PHASE 2 DATABASE UPGRADE
-- Run this AFTER supabase_setup.sql in Supabase -> SQL Editor.
-- This adds the fields/tables needed by the Client and Admin dashboards.

-- Helper used by RLS policies to identify administrators without exposing the profiles table recursively.
create or replace function public.is_vgs_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- Bring bookings in line with the dashboard.
alter table public.bookings add column if not exists project_title text;
alter table public.bookings add column if not exists currency text not null default 'NGN';

update public.bookings
set project_title = coalesce(project_title, project_name, service)
where project_title is null;

-- Project management fields.
alter table public.projects add column if not exists service text;
alter table public.projects add column if not exists progress integer not null default 0;
alter table public.projects add column if not exists budget numeric;
alter table public.projects add column if not exists currency text not null default 'NGN';
alter table public.projects add column if not exists deadline date;

-- Client invoices.
create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.profiles(id) on delete cascade,
  project_id bigint references public.projects(id) on delete set null,
  amount numeric not null default 0,
  currency text not null default 'NGN',
  status text not null default 'pending' check (status in ('pending','paid','overdue','cancelled')),
  due_date date,
  description text,
  created_at timestamptz not null default now()
);

-- Client/admin messages.
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.profiles(id) on delete cascade,
  sender_id uuid references auth.users(id) on delete set null,
  sender_role text not null default 'client' check (sender_role in ('client','admin')),
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.invoices enable row level security;
alter table public.messages enable row level security;

-- Replace overly narrow policies with client + admin access rules.
drop policy if exists "Clients can view own bookings" on public.bookings;
drop policy if exists "Clients can create own bookings" on public.bookings;
create policy "Clients and admins can view bookings"
on public.bookings for select to authenticated
using (auth.uid() = client_id or public.is_vgs_admin());
create policy "Clients can create own bookings"
on public.bookings for insert to authenticated
with check (auth.uid() = client_id);
create policy "Admins can manage bookings"
on public.bookings for all to authenticated
using (public.is_vgs_admin())
with check (public.is_vgs_admin());

-- Projects: clients see their own, admins manage all.
drop policy if exists "Clients can view own projects" on public.projects;
create policy "Clients and admins can view projects"
on public.projects for select to authenticated
using (auth.uid() = client_id or public.is_vgs_admin());
create policy "Admins can manage projects"
on public.projects for all to authenticated
using (public.is_vgs_admin())
with check (public.is_vgs_admin());

-- Invoices: clients see their own; admins manage all.
create policy "Clients and admins can view invoices"
on public.invoices for select to authenticated
using (auth.uid() = client_id or public.is_vgs_admin());
create policy "Admins can manage invoices"
on public.invoices for all to authenticated
using (public.is_vgs_admin())
with check (public.is_vgs_admin());

-- Messages: clients see/send their own; admins can manage all.
create policy "Clients and admins can view messages"
on public.messages for select to authenticated
using (auth.uid() = client_id or public.is_vgs_admin());
create policy "Clients can send messages"
on public.messages for insert to authenticated
with check (auth.uid() = client_id and sender_role = 'client');
create policy "Admins can manage messages"
on public.messages for all to authenticated
using (public.is_vgs_admin())
with check (public.is_vgs_admin());

-- Admins need to be able to view the client list, while normal clients remain restricted to themselves.
drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users and admins can view profiles"
on public.profiles for select to authenticated
using (auth.uid() = id or public.is_vgs_admin());

-- IMPORTANT: after your own VGS account exists, grant yourself admin access with:
-- update public.profiles set role = 'admin' where email = 'YOUR-EMAIL@example.com';
